apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: config-server
    spec:
      imagePullSecrets:
        - name: harbor-bot
      containers:
        - env:
            - name: TZ
              value: "Asia/Tokyo"
          image: registry-jpe2.r-local.net/ecfd-devops-spring-cloud-config/test-configserver:4
          imagePullPolicy: Always
          name: config-server
          ports:
            - containerPort: 8888
              name: app
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: /app/config/application.properties
              subPath: application.properties
              name: config
              readOnly: true
            - mountPath: /home/user1/.ssh/id_rsa.pub
              subPath: id_rsa.pub
              name: config-ssh-keys
              readOnly: true
            - mountPath: /home/user1/.ssh/id_rsa
              subPath: id_rsa
              name: config-ssh-keys
              readOnly: true
            - mountPath: /home/user1/.ssh/known_hosts
              subPath: known_hosts
              name: config-ssh-keys
              readOnly: true
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      volumes:
        - name: config
          projected:
            defaultMode: 288
            sources:
              - configMap:
                  name: config-server
        - name: config-ssh-keys
          projected:
            defaultMode: 288
            sources:
              - configMap:
                  name: config-server-ssh-keys