apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
  name: config-server
spec:
  ports:
    - name: http-app
      port: 8888
      targetPort: app
  selector:
    app: config-server
  type: ClusterIP