repositories:
  - name: kafka-repo
    url: registry-1.docker.io/bitnamicharts
    oci: true

releases:
  - name: kafka
    namespace: test
    createNamespace: false
    chart: kafka-repo/kafka
    version: 26.8.3
    values:
      - ./values.yaml
