apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: "test"
  annotations:
    networking.istio.io/exportTo: "."
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-controller-headless
  namespace: test
  annotations:
    networking.istio.io/exportTo: "."